services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    command: sh ./scripts/start-dev.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PW}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data: