services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: "false"
    command: sh ./scripts/start-deploy.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PW}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data: