services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    command: sh ./scripts/start-deploy.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PW}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: